# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import datetime
import typing

class BarData:
    tradeday: datetime.date
    begin: datetime.datetime
    internal_end: datetime.datetime
    r"""
    内部使用
    """
    open: builtins.float
    high: builtins.float
    low: builtins.float
    close: builtins.float
    volume: builtins.int
    turnover: builtins.float
    openint: builtins.int
    finished: builtins.bool
    barsz_sec: builtins.int
    def __new__(cls) -> BarData: ...
    def __repr__(self) -> builtins.str: ...

class InstBarBuilder:
    def __new__(cls, inst:builtins.str, barsz_sec:typing.Sequence[builtins.int], session_minutes:typing.Sequence[builtins.int], pre_bar_map:typing.Mapping[builtins.int, BarData], zero_vol_bar:builtins.bool) -> InstBarBuilder: ...
    def to_string(self) -> builtins.str: ...
    def on_tick(self, tick:TickData, realtime_feed:builtins.bool) -> tuple[builtins.bool, builtins.list[BarData], typing.Optional[builtins.list[BarData]]]:
        r"""
        返回值，tick是否在此合约的tradesession之内
        closed_this_tick: 本tick内关闭的bar
        updated_this_tick: 收集Bar的实时变化信息，高开低收量，适用每tick推送的场景
        """
    def on_tick_detail(self, tradeday:datetime.date, datetime:datetime.datetime, last:builtins.float, openint:builtins.int, volume:builtins.int, turnover:builtins.float, vol_delta:builtins.int, tnov_delta:builtins.float, realtime_feed:builtins.bool) -> tuple[builtins.bool, builtins.list[BarData], typing.Optional[builtins.list[BarData]]]:
        r"""
        返回值，tick是否在此合约的tradesession之内
        closed_this_tick: 本tick内关闭的bar
        updated_this_tick: 收集Bar的实时变化信息，高开低收量，适用每tick推送的场景
        """
    def on_timer(self, now:datetime.datetime, threshold:datetime.timedelta) -> builtins.list[BarData]:
        r"""
        若last_bar的结束时间小于(now-threshold), 则关闭该bar
        返回关闭的bar
        """

class TickData:
    tradeday: datetime.date
    datetime: datetime.datetime
    last: builtins.float
    openint: builtins.int
    volume: builtins.int
    turnover: builtins.float
    vol_delta: builtins.int
    tnov_delta: builtins.float
    def __new__(cls) -> TickData: ...
    def __repr__(self) -> builtins.str: ...

